### ISSUE TITLE
[Helpers\AuthHelper] generateJWT()

### ISSUE THREAD

**Issue by devalirzayev** [FS-Code/open-appointment-backend#59]
Write a method that generates JWT (JSON Web Token).

`generateJWT( string|array $data ): string`

Method accepts either string or array. If `$data` is array, JSON stringify it. Method should return generated token on success, otherwise should throw an exception. Also generated token should use private key (add private key to `.env` file & `.env.example`) as a secret.

`.env` variable name: `SECRET_KEY`

Possible exceptions:
 - If private key does not exist, `Private key is missing`
 - If `$data` is empty, `data can't be empty`
 
 **Note:** you can't install new third party libraries for JWT generation. To fetch information from `.env` file there is already `DotEnv` library.

**Comment by aytacali** [comment]
Salam, methoddaki datanin icerisinde hansi melumatlar gelecek? email , password ? yoxsa basqa melumatlar da?

**Comment by devalirzayev** [comment]
> Salam, methoddaki datanin icerisinde hansi melumatlar gelecek? email , password ? yoxsa basqa melumatlar da?

her shey gele biler
